import { getProfile } from "@/lib/cortexaApi";

export const dynamic = "force-dynamic";

export default async function ProfilePage() {
  const { snapshot } = await getProfile();

  return (
    <div className="space-y-6">
      <header className="rounded-2xl border border-zinc-200 bg-white p-6">
        <div className="text-sm text-zinc-500">Profile</div>
        <h1 className="mt-1 text-2xl font-semibold tracking-tight">Your monthly profile snapshot</h1>
        <p className="mt-2 text-sm text-zinc-600">
          This is generated by your backend and stored as <code className="rounded bg-zinc-50 px-1">source_type=profile_snapshot</code>.
        </p>
      </header>

      <section className="rounded-2xl border border-zinc-200 bg-white p-6">
        {snapshot ? (
          <pre className="whitespace-pre-wrap text-sm leading-6 text-zinc-800">{snapshot}</pre>
        ) : (
          <div className="text-sm text-zinc-600">
            No profile snapshot yet. It auto-generates monthly (or you can run <code className="rounded bg-zinc-50 px-1">/profile</code> in Telegram).
          </div>
        )}
      </section>
    </div>
  );
}

